platform :ios, '9.0'
use_frameworks!
target 'ZhiHuDaily' do


  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'NSObject+Rx'
  pod 'RxDataSources'

  pod 'HandyJSON'
  pod 'SwifterSwift'
  pod 'Kingfisher'	

  pod 'SwiftyBeaver'

  pod 'Then'

  pod 'R.swift'
  
  pod 'SlideMenuControllerSwift'
  pod 'CFNotify'
  pod 'Closures'
  pod 'SnapKit'
  pod 'AttributedLib'
  pod 'KSPhotoBrowser'

end
