//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 32 images.
  struct image {
    /// Image `Back_White`.
    static let back_White = Rswift.ImageResource(bundle: R.hostingBundle, name: "Back_White")
    /// Image `Field_Button_Highlight_Bg`.
    static let field_Button_Highlight_Bg = Rswift.ImageResource(bundle: R.hostingBundle, name: "Field_Button_Highlight_Bg")
    /// Image `Field_Mask_Bg`.
    static let field_Mask_Bg = Rswift.ImageResource(bundle: R.hostingBundle, name: "Field_Mask_Bg")
    /// Image `Guide_Txt1`.
    static let guide_Txt1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Guide_Txt1")
    /// Image `Guide_Txt2`.
    static let guide_Txt2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Guide_Txt2")
    /// Image `Guide_Txt3`.
    static let guide_Txt3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Guide_Txt3")
    /// Image `Home_Icon_Highlight`.
    static let home_Icon_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Icon_Highlight")
    /// Image `Home_Icon`.
    static let home_Icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Icon")
    /// Image `Home_Image_Mask_Plus`.
    static let home_Image_Mask_Plus = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Image_Mask_Plus")
    /// Image `Home_Image_Mask`.
    static let home_Image_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Image_Mask")
    /// Image `Home_Morepic`.
    static let home_Morepic = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Morepic")
    /// Image `Home_Split`.
    static let home_Split = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Split")
    /// Image `Home_Topmask`.
    static let home_Topmask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Topmask")
    /// Image `Image_Preview`.
    static let image_Preview = Rswift.ImageResource(bundle: R.hostingBundle, name: "Image_Preview")
    /// Image `Menu_Avatar_Mask`.
    static let menu_Avatar_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Avatar_Mask")
    /// Image `Menu_Avatar`.
    static let menu_Avatar = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Avatar")
    /// Image `Menu_Close`.
    static let menu_Close = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Close")
    /// Image `Menu_Dark`.
    static let menu_Dark = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Dark")
    /// Image `Menu_Day`.
    static let menu_Day = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Day")
    /// Image `Menu_Download`.
    static let menu_Download = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Download")
    /// Image `Menu_Enter`.
    static let menu_Enter = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Enter")
    /// Image `Menu_Follow`.
    static let menu_Follow = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Follow")
    /// Image `Menu_Icon_Collect`.
    static let menu_Icon_Collect = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Collect")
    /// Image `Menu_Icon_Events_Clicked`.
    static let menu_Icon_Events_Clicked = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Events_Clicked")
    /// Image `Menu_Icon_Events`.
    static let menu_Icon_Events = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Events")
    /// Image `Menu_Icon_Home_Highlight`.
    static let menu_Icon_Home_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Home_Highlight")
    /// Image `Menu_Icon_Home`.
    static let menu_Icon_Home = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Home")
    /// Image `Menu_Icon_Message_Point`.
    static let menu_Icon_Message_Point = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Message_Point")
    /// Image `Menu_Icon_Message`.
    static let menu_Icon_Message = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Message")
    /// Image `Menu_Icon_Setting`.
    static let menu_Icon_Setting = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Icon_Setting")
    /// Image `Menu_Mask`.
    static let menu_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_Mask")
    /// Image `Menu_New`.
    static let menu_New = Rswift.ImageResource(bundle: R.hostingBundle, name: "Menu_New")
    
    /// `UIImage(named: "Back_White", bundle: ..., traitCollection: ...)`
    static func back_White(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back_White, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Field_Button_Highlight_Bg", bundle: ..., traitCollection: ...)`
    static func field_Button_Highlight_Bg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.field_Button_Highlight_Bg, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Field_Mask_Bg", bundle: ..., traitCollection: ...)`
    static func field_Mask_Bg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.field_Mask_Bg, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Guide_Txt1", bundle: ..., traitCollection: ...)`
    static func guide_Txt1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.guide_Txt1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Guide_Txt2", bundle: ..., traitCollection: ...)`
    static func guide_Txt2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.guide_Txt2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Guide_Txt3", bundle: ..., traitCollection: ...)`
    static func guide_Txt3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.guide_Txt3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Icon", bundle: ..., traitCollection: ...)`
    static func home_Icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Icon_Highlight", bundle: ..., traitCollection: ...)`
    static func home_Icon_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Icon_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Image_Mask", bundle: ..., traitCollection: ...)`
    static func home_Image_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Image_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Image_Mask_Plus", bundle: ..., traitCollection: ...)`
    static func home_Image_Mask_Plus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Image_Mask_Plus, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Morepic", bundle: ..., traitCollection: ...)`
    static func home_Morepic(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Morepic, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Split", bundle: ..., traitCollection: ...)`
    static func home_Split(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Split, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Topmask", bundle: ..., traitCollection: ...)`
    static func home_Topmask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Topmask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Image_Preview", bundle: ..., traitCollection: ...)`
    static func image_Preview(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.image_Preview, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Avatar", bundle: ..., traitCollection: ...)`
    static func menu_Avatar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Avatar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Avatar_Mask", bundle: ..., traitCollection: ...)`
    static func menu_Avatar_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Avatar_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Close", bundle: ..., traitCollection: ...)`
    static func menu_Close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Close, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Dark", bundle: ..., traitCollection: ...)`
    static func menu_Dark(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Dark, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Day", bundle: ..., traitCollection: ...)`
    static func menu_Day(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Day, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Download", bundle: ..., traitCollection: ...)`
    static func menu_Download(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Download, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Enter", bundle: ..., traitCollection: ...)`
    static func menu_Enter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Enter, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Follow", bundle: ..., traitCollection: ...)`
    static func menu_Follow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Follow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Collect", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Collect(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Collect, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Events", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Events(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Events, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Events_Clicked", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Events_Clicked(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Events_Clicked, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Home", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Home_Highlight", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Home_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Home_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Message", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Message(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Message, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Message_Point", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Message_Point(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Message_Point, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Icon_Setting", bundle: ..., traitCollection: ...)`
    static func menu_Icon_Setting(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Icon_Setting, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_Mask", bundle: ..., traitCollection: ...)`
    static func menu_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Menu_New", bundle: ..., traitCollection: ...)`
    static func menu_New(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu_New, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 3 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `KMBannerCell`.
    static let kmBannerCell: Rswift.ReuseIdentifier<KMBannerCell> = Rswift.ReuseIdentifier(identifier: "KMBannerCell")
    /// Reuse identifier `KMStoryListCell`.
    static let kmStoryListCell: Rswift.ReuseIdentifier<KMStoryListCell> = Rswift.ReuseIdentifier(identifier: "KMStoryListCell")
    /// Reuse identifier `KMThemeCell`.
    static let kmThemeCell: Rswift.ReuseIdentifier<KMThemeCell> = Rswift.ReuseIdentifier(identifier: "KMThemeCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `KMStoryboard`.
    static let kmStoryboard = _R.storyboard.kmStoryboard()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "KMStoryboard", bundle: ...)`
    static func kmStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.kmStoryboard)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try kmStoryboard.validate()
    }
    
    struct kmStoryboard: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let kmHomeViewController = StoryboardViewControllerResource<KMHomeViewController>(identifier: "KMHomeViewController")
      let kmMenuViewController = StoryboardViewControllerResource<KMMenuViewController>(identifier: "KMMenuViewController")
      let kmThemeViewController = StoryboardViewControllerResource<KMThemeViewController>(identifier: "KMThemeViewController")
      let name = "KMStoryboard"
      
      func kmHomeViewController(_: Void = ()) -> KMHomeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: kmHomeViewController)
      }
      
      func kmMenuViewController(_: Void = ()) -> KMMenuViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: kmMenuViewController)
      }
      
      func kmThemeViewController(_: Void = ()) -> KMThemeViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: kmThemeViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "Field_Mask_Bg") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Field_Mask_Bg' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Home_Image_Mask") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Home_Image_Mask' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Avatar") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Avatar' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Icon_Setting") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Icon_Setting' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Home_Morepic") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Home_Morepic' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Enter") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Enter' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Icon_Home") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Icon_Home' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Icon_Collect") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Icon_Collect' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Mask") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Mask' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Download") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Download' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Dark") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Dark' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if UIKit.UIImage(named: "Menu_Icon_Message") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Menu_Icon_Message' is used in storyboard 'KMStoryboard', but couldn't be loaded.") }
        if _R.storyboard.kmStoryboard().kmHomeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'kmHomeViewController' could not be loaded from storyboard 'KMStoryboard' as 'KMHomeViewController'.") }
        if _R.storyboard.kmStoryboard().kmMenuViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'kmMenuViewController' could not be loaded from storyboard 'KMStoryboard' as 'KMMenuViewController'.") }
        if _R.storyboard.kmStoryboard().kmThemeViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'kmThemeViewController' could not be loaded from storyboard 'KMStoryboard' as 'KMThemeViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
